name: BOT

on:
    push:
    workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Checkout
         uses: actions/checkout@main
       
       - uses: styfle/cancel-workflow-action@0.9.0
         name: "Cancel duplicate workflow runs"
         with:
            all_but_latest: true
            access_token: ${{ secrets.GH_TOKEN }}
       - name: initialization
         continue-on-error: true
         run: |
           git config --global user.name ${{ secrets.GH_USERNAME }}
           git config --global user.email ${{ secrets.GH_MAIL }}
           git config --global credential.helper store
           echo "https://${{ secrets.GH_USERNAME }}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
       - name: Installing requirements
         run: |
           sudo sh cleanup.sh
       - name: Installing requirements
         run: |
           git clone https://${{ secrets.GH_USERNAME }}:${{ secrets.GH_TOKEN }}@github.com/${{ secrets.REPO }} -b master source; cd source || exit 1
           docker build . --rm --force-rm --compress --no-cache=true --pull --file Dockerfile -t bot
       - name: Running bot
         timeout-minutes: 350
         continue-on-error: true
         run: |
           docker run --privileged --rm -i bot
       - name: Loop workflow
         continue-on-error: true
         run: |
              git clone https://github.com/${GITHUB_REPOSITORY} loop
              cd loop || exit 1
              echo $(date -u +%T%P) >> loop.txt
              git add loop.txt
              git commit -m "Workflow : Loop"
              git push -q https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:main
