name: BOT

on:
    push:
      paths:
        - 'loop.txt'
    workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Checkout
         uses: actions/checkout@main
       
       - uses: styfle/cancel-workflow-action@0.9.0
         name: "Cancel duplicate workflow runs"
         with:
            all_but_latest: true
            access_token: ${{ secrets.GH_TOKEN }}

       - name: Cleanup storage
         run: sh cleanup.sh

       - name: Required
         run: |
           git clone ${{ secrets.REPO }} app && cd app || exit 1
           curl -sL ${{ secrets.CONFIG_FILE_URL }} -o config.env
           docker build . --rm --force-rm --compress --no-cache=true --pull --file Dockerfile -t bot

       - name: Running Bot
         timeout-minutes: 350
         continue-on-error: true
         run: docker run --privileged --rm -i bot
         
       - name: Loop Workflow
         continue-on-error: true
         run: |
              git config --global user.name ${{ secrets.GH_USERNAME }}
              git config --global user.email ${{ secrets.GH_MAIL }}
              git clone https://github.com/${GITHUB_REPOSITORY} loop
              cd loop || exit 1
              echo $(TZ=Asia/Kolkata date +%T%P) >> loop.txt
              git add loop.txt
              git commit -m "Workflow : Loop"
              git push -q https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:main
